AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Calculator Lambda App

Resources:
  CalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: calculator.lambda_handler
      Runtime: python3.8
      CodeUri: .
      MemorySize: 128
      Timeout: 100
      Events:
        CalculatorApi:
          Type: Api
          Properties:
            Path: /{operation}/{a}/{b}
            Method: get

Outputs:
  CalculatorApiUrl:
    Description: "API Gateway endpoint URL for Calculator function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
